server:
  port: 8082

spring:
  application:
    name: springboot-05-security
  data:
    mongodb:
      host: 192.168.90.142
      port: 27017
      database: admin
      username: root
      password: '123456'
      authentication-database: admin



