server:
  port: 8082

spring:
  application:
    name: springboot-05-security
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/auth?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8&allowMultiQueries=true&rewriteBatchedStatements=true
  redis:
    host: 124.71.178.170
    port: 6379
    password: bS6XD8kpwysb
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        max-wait: 2000
        max-idle: 50
        min-idle: 8
        time-between-eviction-runs: 1000
    database: 11
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml


